### ISSUE TITLE
Redirect within same subsection shows empty unit

### ISSUE THREAD

**Issue by Tonkiro** [eduNEXT/flow-control-xblock#18] opened 2017-03-31 15:42 UTC
![2017-03-31](https://cloud.githubusercontent.com/assets/18026535/24557812/65b8d984-1639-11e7-816a-42ea29401e08.png)
Instead of redirecting, redirect within same subsection shows an empty unit for me.

Open edX release Ficus.1 native on AWS EC2.

Parameters: 
Comparison type: not equal to
Score percentage: 100
Action: redirect to a given unit in the same subsection
Tab to redirect to: 1 (from unit 2), 2 (from unit 3)

**Comment by felipemontoya** [comment] 2017-04-03 09:53
Hi @Tonkiro! thanks for the report.

@juancamilom do you think this might be happening because of changes to the sequence html in ficus?
@diegomillan can take a look when you are back?

**Comment by diegomillan** [comment] 2017-04-03 13:50
I will take a look at this @felipemontoya. Thanks @Tonkiro for the report!

**Comment by Tonkiro** [comment] 2017-04-04 13:39
Thanks guys. That's great. I can't rule out yet that it is some kind of configuration problem on my end. I'm just starting with my open edx site and there is still much to learn for me. So please check if the same settings result in the same behaviour for you. I wouldn't want to waste your time.

**Comment by juancamilom** [comment] 2017-04-04 19:13
@felipemontoya  yes, the problem is most likely due to a change in the way the sequences are handled, but It appeared before the ficus upgrade.
@Tonkiro we do get the same behaviour, so your configuration is probably fine.   We'll look into it.  In the mean time, you can always use the other options, "redirect using jump_to_id"  . It also works for redirecting to units in the same subsection. the only downside is that you'll have a page reload, but other that that, it will work fine and get you out of trouble for now.

**Comment by diegomillan** [comment] 2017-04-19 22:15
Hi @Tonkiro, we fixed this issue with  #19. I encourage you to try the latest version over Ficus. I'm going to close this.

**Closed by diegomillan** 2017-04-19 22:15 UTC
